### ISSUE TITLE
一些关于翻译功能方面存在的问题

### ISSUE THREAD

**Issue by Twilight-Kirisame** [Icexbb/SekaiTools#20]
### 优先级

P0

### 填写你遇到bug所用的版本

1.2.9.1212

### Bug 描述

①在翻译分行时翻译输入框一栏最大为什么只能分两行（在翻译对话的时候经常会出现两行以及以上换行的情况），现有的两行分行完全不够用。
②在翻译中导入GUI界面上的常用的特殊符号的时候经常发生闪退！
③在使用翻译文本导入txt文件时（在已经导入剧本的asset文件的情况下），显示“翻译数据不适用于此剧本”，导致无法从上次翻译好的地方继续开始翻译。

### 轴机输入

暂无

### 轴机输出

暂无

**Comment by Icexbb** [comment]
2 fixed in [f87a7ea](https://github.com/Icexbb/SekaiTools/commit/f87a7ea0371518f5d8e35f92faf564158e0d9cdb)

**Comment by Icexbb** [comment]
3 已消失
1 fixed in 3dfdb995e1755353e188e09d2d8790761b2112eb
