### ISSUE TITLE
关于自定义输出过滤器

### ISSUE THREAD

**Issue by aq1340284239** [Icexbb/SekaiTools#7]
希望能加入自定义输出过滤器内容，可以根据字幕样式删除输出内容，例如删除所有样式为sreen的内容（即删除注释），删除所有样式为character的内容（即删除说话人）

**Comment by Icexbb** [comment]
enhanced in [1.2.10.1214](https://github.com/Icexbb/SekaiTools/commit/b8e234e5a556c9bbe6020b3cae8adc62fa57fed8)
